name: build-images
on: [pull_request]
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ghcr.io/k8snetworkplumbingwg/multi-networkpolicy-iptables
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${REPOSITORY}:latest-amd64
