name: push-master
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      REPOSITORY: ghcr.io/k8snetworkplumbingwg/multi-networkpolicy-iptables
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: github.repository == 'k8snetworkplumbingwg/multi-networkpolicy-iptables'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push to GitHub Container Registry
        if: github.repository == 'k8snetworkplumbingwg/multi-networkpolicy-iptables'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/k8snetworkplumbingwg/multi-networkpolicy-iptables:latest-amd64
            ghcr.io/k8snetworkplumbingwg/multi-networkpolicy-iptables:snapshot-amd64

      - name: Create manifest for multi-arch images
        if: github.repository == 'k8snetworkplumbingwg/multi-networkpolicy-iptables'
        run: |
          docker manifest create ${REPOSITORY}:snapshot ${REPOSITORY}:snapshot-amd64
          docker manifest annotate ${REPOSITORY}:snapshot ${REPOSITORY}:snapshot-amd64 --arch amd64
          docker manifest push ${REPOSITORY}:snapshot
          docker manifest create ${REPOSITORY}:latest ${REPOSITORY}:latest-amd64
          docker manifest annotate ${REPOSITORY}:latest ${REPOSITORY}:latest-amd64 --arch amd64
          docker manifest push ${REPOSITORY}:latest

